export const NAMES = {
  all: "All Areas",
  systems: "Systems",
  ai: "Artificial Intelligence",
  security: "Computer Security",
  hpc: "High Performance Computing",
  ml: "Machine Learning",
  cv: "Computer Vision",
  nlp: "Natural Language Processing",
  web: "The Web & Information Retrieval",
  theory: "Theory",
  arch: "Computer Architecture",
  networks: "Computer Networks",
  db: "Databases",
  eda: "Design Automation",
  embedded: "Embedded & Real-Time Systems",
  mobile: "Mobile Computing",
  measurement: "Measurement & Performance Analysis",
  os: "Operating Systems",
  proglang: "Programming Languages",
  software: "Software Engineering",
  algo: "Algorithms & Complexity",
  crypto: "Cryptography",
  logic: "Logic & Verification",
  graphics: "Computer Graphics",
  inter: "Interdisciplinary Area",
  bio: "Computational Biology & Bioinformatics",
  edu: "Computer Science Education",
  ecocomp: "Economics & Computation",
  hci: "Human-Computer Interaction",
  robotics: "Robotics",
  visualisation: "Visualization",
};

export const CONF_NAMES = {
  asplos: "ASPLOS",
  hpca: "HPCA",
  isca: "ISCA",
  micro: "MICRO",
  ccs: "CCS",
  ndss: "NDSS",
  oakland: "Oakland",
  usenixsec: "USENIX Security",
  pets: "PoPETs",
  tifs: "IEEE TIFS",
  tdsc: "IEEE TDSC",
  sc: "SC",
  hpdc: "HPDC",
  ics: "ICS",
  tpds: "TPDS",
  podc: "PODC",
  vldb: "VLDB",
  sigmod: "SIGMOD",
  icde: "ICDE",
  pods: "PODS",
  dac: "DAC",
  iccad: "ICCAD",
  emsoft: "EMSOFT",
  rtas: "RTAS",
  rtss: "RTSS",
  imc: "IMC",
  sigmetrics: "SIGMETRICS",
  mobicom: "MobiCom",
  mobisys: "MobiSys",
  sensys: "SenSys",
  tmc: "TMC",
  sigcomm: "SIGCOMM",
  nsdi: "NSDI",
  tcns: "TCNS",
  tnsm: "TNSM",
  tgc: "TGC",
  tnse: "TNSE",
  infocom: "INFOCOM",
  tsipn: "TSIPN",
  sosp: "SOSP",
  osdi: "OSDI",
  eurosys: "EuroSys",
  fast: "FAST",
  usenixatc: "USENIX ATC",
  pldi: "PLDI",
  popl: "POPL",
  oopsla: "OOPSLA",
  icfp: "ICFP",
  fse: "FSE",
  icse: "ICSE",
  ase: "ASE",
  issta: "ISSTA",
  tse: "TSE",
  nips: "NeurIPS",
  kdd: "KDD",
  icml: "ICML",
  iclr: "ICLR",
  tnnls: "TNNLS",
  colt: "COLT",
  acl: "ACL",
  emnlp: "EMNLP",
  naacl: "NAACL",
  www: "WWW",
  sigir: "SIGIR",
  icdm: "ICDM",
  aaai: "AAAI",
  ijcai: "IJCAI",
  tai: "TAI",
  aamas: "AAMAS",
  cvpr: "CVPR",
  eccv: "ECCV",
  iccv: "ICCV",
  ismb: "ISMB",
  recomb: "RECOMB",
  ec: "EC",
  wine: "WINE",
  sigcse: "SIGCSE",
  siggraph: "SIGGRAPH",
  eurographics: "Eurographics",
  "siggraph-asia": "SIGGRAPH Asia",
  chiconf: "CHI",
  uist: "UIST",
  ubicomp: "Ubicomp",
  tcss: "TCSS",
  taffc: "TAFFC",
  percom: "PerCom",
  icra: "ICRA",
  iros: "IROS",
  rss: "RSS",
  trob: "TROB",
  vis: "VIS",
  vr: "VR",
  focs: "FOCS",
  soda: "SODA",
  stoc: "STOC",
  crypto: "CRYPTO",
  eurocrypt: "EUROCRYPT",
  lics: "LICS",
  cav: "CAV",
};

export const CONFS = {
  systems: {
    arch: ["asplos", "hpca", "isca", "micro"],
    security: ["ccs", "ndss", "oakland", "usenixsec", "pets", "tifs", "tdsc"],
    hpc: ["sc", "hpdc", "ics", "tpds", "podc"],
    db: ["vldb", "sigmod", "icde", "pods"],
    eda: ["dac", "iccad"],
    embedded: ["emsoft", "rtas", "rtss"],
    measurement: ["imc", "sigmetrics"],
    mobile: ["mobicom", "mobisys", "sensys", "tmc"],
    networks: [
      "sigcomm",
      "nsdi",
      "tcns",
      "tnsm",
      "tgc",
      "tnse",
      "infocom",
      "tsipn",
    ],
    os: ["sosp", "osdi", "eurosys", "fast", "usenixatc"],
    proglang: ["pldi", "popl", "oopsla", "icfp"],
    software: ["fse", "icse", "ase", "issta", "tse"],
  },
  ai: {
    ml: ["nips", "kdd", "icml", "iclr", "tnnls", "colt"],
    nlp: ["acl", "emnlp", "naacl"],
    web: ["www", "sigir", "icdm"],
    ai: ["aaai", "ijcai", "tai", "aamas"],
    cv: ["cvpr", "eccv", "iccv"],
  },
  inter: {
    bio: ["ismb", "recomb"],
    ecocomp: ["ec", "wine"],
    edu: ["sigcse"],
    graphics: ["siggraph", "eurographics", "siggraph-asia"],
    hci: ["chiconf", "uist", "ubicomp", "tcss", "taffc", "percom"],
    robotics: ["icra", "iros", "rss", "trob"],
    visualisation: ["vis", "vr"],
  },
  theory: {
    algo: ["focs", "soda", "stoc"],
    crypto: ["crypto", "eurocrypt"],
    logic: ["lics", "cav"],
  },
};
